### ISSUE TITLE
Add a touch controller to the Game

### ISSUE THREAD

**Issue by Ouadie** [FullScreenShenanigans/FullScreenMario#1]
It will be great if the game has a controller like this https://bytebucket.org/rileytestut/gba4ios/raw/3e028f00e946eeac710ba3243f37170d1c780e83/Skins/Purple/portrait%402x.png ?

**Comment by JoshuaKGoldberg** [comment]
@Ouadie development of a touch controller has started in the [touch-controller](https://github.com/FullScreenShenanigans/FullScreenMario/tree/touch-controller) branch! I know you've been waiting for this an ungodly amount of time, so it feels excellent to finally start work on it.

**Comment by JoshuaKGoldberg** [comment]
@Ouadie The touch-controller branch is merged into master. You should be able to use the touch controller now.

**Comment by JoshuaKGoldberg** [comment]
No complaints yet. Closing issue; if there are glitches please open a new one!
