### ISSUE TITLE
Castle stretch areas should make pass/fail noises

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [FullScreenShenanigans/FullScreenMario#191]

**Comment by janjtv** [comment]
I just played the original mario and there was no sound for passing or failing, but in the GBC[Citation needed] or DS version there is one.

**Comment by JoshuaKGoldberg** [comment]
Interesting!

**Comment by janjtv** [comment]
## News just in
In SMB deluxe there are pass fail noises. The pass noise is the coin/pause sound and the fail sound is just a generic fail noise that isn't anywhere in the NES game. I haven't found a way to dump it so i cant supply that sound here :(.

**Comment by JoshuaKGoldberg** [comment]
> News just in

Well ok then. 


...and yes, that fail noise is the problem I found as well. If/once [GBSEmulatr](https://github.com/FullScreenShenanigans/FullScreenPokemon/tree/master/modules/GBSEmulatr) from the FullScreenPokemon gets pulled in, that would likely solve the problem.

**Comment by janjtv** [comment]
Here https://github.com/FullScreenShenanigans/FullScreenMario/pull/265

**Comment by janjtv** [comment]
Did you add using the sound? If yes this one can be closed.

**Comment by JoshuaKGoldberg** [comment]
The physical audio file was added, but not the code to play it.

**Comment by janjtv** [comment]
Okay, thanks, cant wait for it to be added!

**Comment by JoshuaKGoldberg** [comment]
Thanks @janjtv for finding the sound! I'm curious, where did you get it from?

**Comment by janjtv** [comment]
@JoshuaKGoldberg Well, the only place it plays the fail sound without background music is in the fortune games bad fortune. So i recorded that and cut out only the fail sound.
