### ISSUE TITLE
Half-size PixelRendr sources (PixelRendr/issues/9)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [FullScreenShenanigans/FullScreenMario#236]
Requires #71 (to avoid performance issues).

See https://github.com/FullScreenShenanigans/PixelRendr/issues/9

**Comment by BigG** [comment]
Hi Joshua, great project. Is there any easy way to change main character or mushroom spite? I have already read all you posted but it is really hard to find an operative way starting from a simple image. Can you help me?

**Comment by JoshuaKGoldberg** [comment]
Sure! A few people have mentioned this recently, so I hope to write a guide soon.

Sprites are stored in /settings/sprites.js. You'll want to use the /GameStartr/utils/ImageReadr/ImageReadr.html utility to convert an image to that format. Does that help?

**Comment by BigG** [comment]
Hi and thank you for the quick reply.
To be honest I already tryed but a "Processing" message it is showed (ant it never ends). In the console log I see Uncaught TypeError: Cannot read property 'process' of undefined where I am wrong?

Thanks,
B.G.

**Comment by JoshuaKGoldberg** [comment]
That sounds like a bug - can you make a new issue for it?

**Comment by BigG** [comment]
Ok, done.
Btw seems so weird; please consider me available for further test or investigations.
Thanks!

**Comment by JoshuaKGoldberg** [comment]
Note: mirrored in PixelRendr issue tracker as https://github.com/FullScreenShenanigans/PixelRendr/issues/9. Once that is added in, a branch here should use that updated reference and update all the sprites. FullScreenPokemon and the image utilities will need to be updated as well.
