### ISSUE TITLE
Use individual .js map files in a settings/maps folder

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [FullScreenShenanigans/FullScreenMario#240]
For development code, it's acceptable to have a large number of script includes. The map files should then be concatenated into the settings/maps.js file for production output.

**Comment by Diogenesthecynic** [comment]
Looking at you, @joechip504 :)

**Comment by joechip504** [comment]
;)

**Comment by joechip504** [comment]
https://github.com/gruntjs/grunt-contrib-concat/blob/master/README.md

Looks promising! I'll play with it

**Comment by JoshuaKGoldberg** [comment]
bump
