### ISSUE TITLE
editor locks up when mario bumps a block

### ISSUE THREAD

**Issue by burrows-labs** [FullScreenShenanigans/FullScreenMario#245]
Chromium: 41.0.2272.101 (Developer Build)

To reproduce, open the editor, place a block, hit play, bump into the block.

corresponding error output

```
Uncaught TypeError: Cannot read property 'updateSize' of undefined GameStartr.js:580
addThing
animateSolidContents
TimeHandlr.self.handleEvents
(anonymous function) 
run
GamesRunnr.self.upkeepTimed
GamesRunnr.self.upkeep
```

**Comment by JoshuaKGoldberg** [comment]
Glitch confirmed. Working on solution..

**Comment by JoshuaKGoldberg** [comment]
Thanks for the bug report!

**Comment by burrows-labs** [comment]
No problem, thanks for prompt fix.

**Comment by JoshuaKGoldberg** [comment]
My pleasure! I don't have much time to work on FullScreenMario specifically, but anytime you find something wrong I'll get it fixed ASAP.
