### ISSUE TITLE
bricks don't produce coins/mushrooms/etc when you bump them in the editor

### ISSUE THREAD

**Issue by burrows-labs** [FullScreenShenanigans/FullScreenMario#247]
To reproduce,

Open editor, place a brick, bump it -- the contents don't come out.

I put this line in collideBottomBrick,

```
console.log("contents(" + thing.constructor.name + "): " + thing.contents, thing.constructor.prototype.contents);
```

Output looks like this,

contents(Brick): false undefined

**Comment by JoshuaKGoldberg** [comment]
Glitched confirmed, working on solution...
