### ISSUE TITLE
Custom sprite creation

### ISSUE THREAD

**Issue by BigG** [FullScreenShenanigans/FullScreenMario#263]
Hi there, just to open a new issue on custom sprite creation.
Tool located in /GameStartr/utils/ImageReadr/ImageReadr.html if used as image loader and mapper return a never ends "Working on" message. No error is reised but in the console log Uncaught TypeError: Cannot read property 'process'

**Comment by JoshuaKGoldberg** [comment]
You're very right -- this broke from the PixelRendr conversion to Typescript. Making a fix now...

**Comment by JoshuaKGoldberg** [comment]
Fixed by #264.

**Comment by BigG** [comment]
Great!!! Thanks a lot
