### ISSUE TITLE
Custom Sprite Creation

### ISSUE THREAD

**Issue by joshuamauldin** [FullScreenShenanigans/FullScreenMario#273]
I'm trying to create my own sprites, or edit others. Could you point me in the right direction?

**Comment by JoshuaKGoldberg** [comment]
Definitely. The documentation is a bit spread out (sorry about that!) but the most helpful things should be:
* [Explanation of how it works](https://github.com/FullScreenShenanigans/PixelRendr)
* [Utility to convert images to sprites](https://github.com/FullScreenShenanigans/GameStartr/tree/master/Source/Utilities/ImageReadr)

Sprites are stored in [Source/settings/sprites.js](https://github.com/FullScreenShenanigans/PixelRendr) as strings. The hierarchy is similar to class names, where library.Character.Beetle.normal.normal is the regular Beetle sprite.

**Comment by joshuamauldin** [comment]
Thank you! If I open the utility in Chrome, it's missing the JS files. I've hooked up grunt and installed the required files, but it doesn't seem to generate any JS files.

**Comment by JoshuaKGoldberg** [comment]
Oh you're absolutely correct, the directory never got updated with the move to TypeScript. Fixing it now...

**Comment by JoshuaKGoldberg** [comment]
Should be fixed! Thanks for reminding me this needed to be done; I'll spin the ImageReadr utility into a separate repo under FullScreenShenanigans and post here when it's ready. In the meantime, the version under GameStartr/Source/Utilities should work.

**Comment by JoshuaKGoldberg** [comment]
https://github.com/FullScreenShenanigans/ImageReadr/ should be good to go. After you clone it, Source/index.html should work.
