### ISSUE TITLE
How to play?

### ISSUE THREAD

**Issue by ogregoire** [FullScreenShenanigans/FullScreenMario#279]
The instructions say to download and extract a zip file, open the `index.html` file and enjoy.

So I downloaded the file, there was no `index.html` at the root but only under `Sources`. I opened that file in Firefox, but it was only a black page with a title and the description of the game. The instructions said to use Chrome, so I made sure my version of Chrome was the last and I opened the file again in that browser. I got the same result.

So... how to play (for non coders)? And if needed please update the instructions in the `README.md`.

**Comment by JoshuaKGoldberg** [comment]
Hey ogregoire,

That's odd, I could have sworn I updated the readme recently; it's linking to very old instructions. 

To start playing immediately, go to [Releases](https://github.com/FullScreenShenanigans/FullScreenMario/releases]), and follow the same steps you already did there.

**Comment by ogregoire** [comment]
Yep, it's now okay. Thanks!
