### ISSUE TITLE
Latest Google Chrome EightBittr.js Error

### ISSUE THREAD

**Issue by Coderwelsch** [FullScreenShenanigans/FullScreenMario#306]
While using the newest browsers such as Google Chrome - i get the following error:
**Uncaught TypeError: Cannot set property style of #<HTMLElement> which has only a getter** at line: 651. The game crashes at this point and its incredible to play.

**Comment by JoshuaKGoldberg** [comment]
That sounds like a glitch that was fixed a little while back. Are you on the last commit on master? If so, can you post a little more information? Specifically, a screenshot of the error & callstack along with the game?

**Comment by Coderwelsch** [comment]
I  have updated it to the newest version of the script and its working like a charm. But after updating to the newest release i could not longer use something like **var FSM = new FullscreenMario( { settings...} );** to initialize my own Mario game. There is another solution for that? Best regards, Joseph

**Comment by JoshuaKGoldberg** [comment]
Yup - **var FSM = new FullScreenMario.FullScreenMario( {settings...} );**

The FullScreenMario class is now a part of the FullScreenMario namespace. It looks a little silly from the JavaScript side, but makes organizing the TypeScript interfaces and classes much easier.

I'll update the [Getting Started doc](https://github.com/FullScreenShenanigans/FullScreenMario/blob/master/Getting%20Started.md) to explicitly mention this, as you're probably not the first to have this question. I'll also close this issue, but just for the sake of issue tracking - feel free to keep posting!
