### ISSUE TITLE
Custom sprites

### ISSUE THREAD

**Issue by jontewks** [FullScreenShenanigans/FullScreenMario#332]
Hello. 

I'm having trouble adding custom sprites. I've been able to create a block like element that acts as I want, but I tried using imagereadr to create a custom sprite for it, and am having trouble. The sprite output seems to chance with the size of the image I use to create the sprite in imagereadr, is there a size that I should upload to imagereadr to get the right output?

**Comment by JoshuaKGoldberg** [comment]
> sprite output changes with size of the image

That's correct, it doesn't resize the image at all. You'll have to take in an image that's the same size, in pixels, as what you want to output. As an example:
![block one](https://cloud.githubusercontent.com/assets/3335181/11416545/894eae36-93c3-11e5-8161-7f4981cfc662.gif)

Love what you're doing with jontewks.github.io by the way :)

**Comment by jontewks** [comment]
Thanks! I see what you sent is 16px, and that worked, I was using images that were too large and they came out strange. I'm trying to get a nice looking github logo for one of those blocks that will redirect to my github profile when struck, and then one for blog, email, and twitter haha.

**Comment by JoshuaKGoldberg** [comment]
Cool - let me know when it's done!

**Comment by jontewks** [comment]
Will do, I really appreciate the help. Got the github block working!
