### ISSUE TITLE
Try out sprite lazy loading

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [FullScreenShenanigans/FullScreenMario#71]
The entire library takes ~1-2 seconds so in theory this could actually make startup time much better.

**Comment by Diogenesthecynic** [comment]
Further thoughts: there should be an API to greedily load everything, such as during a game pause.

**Comment by JoshuaKGoldberg** [comment]
Linked to https://github.com/FullScreenShenanigans/PixelRendr/tree/partial-renders. It's mostly working, so 10.1 release is very reasonable.

**Comment by JoshuaKGoldberg** [comment]
...and it's done! @b2323cf1c11d3d36798e3cd1c64c2381e291bee0

Only one issue introduced: #286
